### PR TITLE
add quickfix for readonly properties

### PR DESCRIPTION
**Pull request by rogergl**
This is the first attempt to implement a quick fix to create read only properties

### CODE REVIEW

**Comment by basarat** [comment]
Cool. Better if we make it a generic `CreateReadonlyProperty` quick fix (instead of a `CreatePropertyFromConstructorArg`). 

The code can remain as it is, supporting additional locations (besides constructor arg) can come later. Just change the name :)

**Comment by basarat** [comment]
@rogergl awesome! thanks :rose: 

Github tip: People don't get notified about PR changes unless you leave a message (after your commit) :checkered_flag:

**Comment by basarat** [comment]
Thanks! I can only imagine your satisfaction though. The first quickfix is truly empowering and fun to write :) 

wrapinreadonlyproperty

**Comment by rogergl** [comment]
Yes it was a really nice experience. Any more ideas for some 'missing' quickfixes ?

**Comment by nycdotnet** [comment]
https://github.com/TypeStrong/atom-typescript/issues/112

**Pull request merged**
