### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jonathandturner**
You need git in the path for autocomplete-plus.

### CODE REVIEW

**Comment by basarat** [comment]
Thanks! Makes me 😔. Will investigate.

**Comment by jonathandturner** [comment]
Bah, 'You' shouldn't be capitalized.  That's what I get for submitting PRs on a bus in the morning.

**Comment by basarat** [comment]
> Bah, 'You' shouldn't be capitalized

I'll take care of it :+1:

**Comment by basarat** [comment]
@jonathandturner I asked the `autocomplete-plus` team. It shouldn't be required

image

**Comment by basarat** [comment]
(ref : https://gitter.im/atom-community/autocomplete-plus?at=54d933a8938f0fd216cf1bcb)

@jonathandturner can I get the details of the error you had?

**Comment by joefitzgerald** [comment]
`autocomplete-plus` doesn't need `git` in your PATH. `apm` needs `git` in your PATH. It's how package installation works.

**Comment by basarat** [comment]
@joefitzgerald awesome Thanks!

**Comment by joefitzgerald** [comment]
Portable `git` is bundled with the Windows distribution - on other platforms it is assumed git is in the PATH. Ref: 

* https://github.com/atom/apm/blob/457b87b683118feaa1295742b62cbfea46dfaa41/src/git.coffee#L47-L50
* https://github.com/atom/apm/blob/11f10075e7f060602ddd58e1fb2e0c91e0ed3b01/src/install.coffee#L170
* https://github.com/atom/apm/blob/11f10075e7f060602ddd58e1fb2e0c91e0ed3b01/src/install.coffee#L173-L181

**Comment by basarat** [comment]
@jonathandturner perhaps you tried on a `mac`?

**Comment by joefitzgerald** [comment]
Macs have git in their path by default, unless they are prehistoric.

```
$ which -a git
/usr/local/bin/git
/usr/local/bin/git
/usr/bin/git
```

**Comment by joefitzgerald** [comment]
Said another way, you should not be able to install `atom-typescript` without `git` in your path either :smile:.

**Comment by basarat** [comment]
looking at https://github.com/atom/apm/blob/11f10075e7f060602ddd58e1fb2e0c91e0ed3b01/src/install.coffee#L174-L202 I see they do show an error for windows. So I'll just be safe and make it a requirement :smile:

**Comment by joefitzgerald** [comment]
Just phrase it such that you make clear it's not a requirement of your package but of installing _any_ atom package.

**Pull request merged**
