### PR TITLE
Feat/language todo support

### PR DESCRIPTION
**Pull request by googol7**
[x] All compiled assets are included (atom packages are git tags and hence the built files need to be a part of the source control)

see https://github.com/TypeStrong/atom-typescript/issues/848

support https://github.com/atom/language-todo single line comments:
    // TODO
    // FIXME
    // CHANGED
    // XXX
    // IDEA
    // HACK
    // NOTE
    // REVIEW
    // NB
    // BUG

### CODE REVIEW

**Comment by googol7** [comment]
Actually these two files should be modified instead as they are referenced by `scripts/grammar.js`:

https://raw.githubusercontent.com/Microsoft/TypeScript-TmLanguage/master/TypeScript.YAML-tmLanguage

https://raw.githubusercontent.com/Microsoft/TypeScript-TmLanguage/master/TypeScriptReact.YAML-tmLanguage

**Comment by googol7** [comment]
There’s already an issue here: https://github.com/Microsoft/TypeScript-TmLanguage/issues/181

**Comment by basarat** [comment]
@googol7 is it good to merge?

**Comment by googol7** [comment]
@basarat: I'd prefer to wait (a little longer) for the merge of this PR here as it would solve the problem more generally for all: https://github.com/Microsoft/TypeScript-TmLanguage/pull/222

Only if that won't be merged I'd merge this PR here.

**Comment by googol7** [comment]
The problem should now have been solved with this PR https://github.com/Microsoft/TypeScript-TmLanguage/pull/257 See also this issue: https://github.com/Microsoft/TypeScript-TmLanguage/issues/181

**Comment by dsifford** [comment]
@googol7 What needs to happen to get this updated in atom? (Sorry in advance for my ignorance)

**Comment by googol7** [comment]
actually only `npm run build` has to be run and with a new version of atom-typescript we should have this fix available.

**Pull request closed without merging**
