### PR TITLE
Implement go to declaration with hyperclick provider

### PR DESCRIPTION
**Pull request by wingyplus**
Hi 

I see #448 talk about this.​ Any suggestions are welcome.

### CODE REVIEW

**Comment by basarat** [comment]
thanks @wingyplus :rose: :heart: https://github.com/TypeStrong/atom-typescript/releases/tag/10.0.0

**Comment by wingyplus** [comment]
@basarat It doesn't work. Is it compile manually?

**Comment by basarat** [comment]
> Is it compile manually?

sadly. As atom packages are essentially just `git tags` so whatever is in git is what makes it to the user system (other than `npm install`) :rose:

**Comment by tlaverdure** [comment]
Should this only work for typescript files? It seems to be activation on all file types like css, less, scss, html...

**Comment by athyuttamre** [comment]
This is a big step up! Thanks for implementing!

**Comment by wingyplus** [comment]
@tlaverdure hyperclick enabled all filetypes. but in feature "go to declaration" work only typescript filetypes (`.ts` and `.tsx`).

**Comment by tlaverdure** [comment]
Maybe using the alt key would be better so it doesn't conflict with default atom functionality.

**Pull request merged**
