### PR TITLE
Adds anonymous Type/Method/Object and Basic Generics support

### PR DESCRIPTION
**Pull request by xperiments**
Adds anonymous Type/Method/Object and Basic Generics support
Removed /* implement-me */ output comment
Added “Tests” at bottom

### CODE REVIEW

**Comment by xperiments** [comment]
Here the simple "tests"

enum EnumTest{
    one,two
}
class FixTests{

    public static STATIC_METHOD():typeof FixTests{ return FixTests }
    public instanceMethod():FixTests{ return this;}
    public instanceGeneric<T>(a:T):T{ return a;}
    constructor(){
        this.simple(true,1,'1',/1/g,null,undefined);
        this.methods( this.instanceMethod, FixTests.STATIC_METHOD );
        this.enums( EnumTest, EnumTest.one );
        this.castedMembers(
            <HTMLElement>{},
            <{x:number; y:number}>{},
            <{fn:(e:FixTests)=>FixTests}>{}
        );
        this.inlineMethods(():number=>{ return -1;});
        this.inlineObjects({
            quickFix:new FixTests,
            type:FixTests,
            step:EnumTest.two
            });
        this.genericMethod( this.instanceGeneric, this.instanceGeneric<FixTests>(this) );

    }
}

**Comment by basarat** [comment]
I've added you as a collab. Feel free to merge and then publish :rose: https://github.com/TypeStrong/atom-typescript/blob/master/CONTRIBUTING.md#publishing

**Comment by xperiments** [comment]
Sweet!!

Done the merge but publishing is not working because I am getting this error when doing "apm publish patch"

npm ERR! Darwin 13.4.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "version" "patch" "-m" "Prepare %s release"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1

npm ERR! Git working directory not clean.
npm ERR! M lib/typings/q/Q.d.ts
npm ERR! M node_modules/grunt-ts/tasks/modules/amdLoader.js
npm ERR! M node_modules/grunt-ts/tasks/modules/amdLoader.ts
npm ERR! M node_modules/grunt-ts/tasks/modules/cacheUtils.js
npm ERR! M node_modules/grunt-ts/tasks/modules/cacheUtils.ts
npm ERR! M node_modules/grunt-ts/tasks/modules/compile.js
npm ERR! M node_modules/grunt-ts/tasks/modules/compile.ts
npm ERR! M node_modules/grunt-ts/tasks/modules/html2ts.js
npm ERR! M node_modules/grunt-ts/tasks/modules/html2ts.ts
npm ERR! M node_modules/grunt-ts/tasks/modules/interfaces.d.ts
npm ERR! M node_modules/grunt-ts/tasks/modules/reference.js
npm ERR! M node_modules/grunt-ts/tasks/modules/reference.ts
npm ERR! M node_modules/grunt-ts/tasks/modules/templateCache.js
npm ERR! M node_modules/grunt-ts/tasks/modules/templateCache.ts
npm ERR! M node_modules/grunt-ts/tasks/modules/transformers.js
npm ERR! M node_modules/grunt-ts/tasks/modules/transformers.ts
npm ERR! M node_modules/grunt-ts/tasks/modules/utils.js
npm ERR! M node_modules/grunt-ts/tasks/modules/utils.ts
npm ERR! M node_modules/grunt-ts/tasks/ts.js
npm ERR! M node_modules/grunt-ts/tasks/ts.ts
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xperiments/Desktop/ATOM-TYPESCRIPT/atom-typescript/npm-debug.log


I have tried to clean the repo with all possible ways I kwow to do it... without success...

Can you help me?

Thanks!!

**Comment by basarat** [comment]
> Git working directory not clean.

Should be clean and *all pushed* i.e. local should match `master` before you can do an `apm publish patch` :rose:

**Comment by xperiments** [comment]
Yes, but my problem is...

if I clone the repo, and do a git status... I see that the cloned version has already the not "clean" files..

npm ERR! M lib/typings/q/Q.d.ts
npm ERR! M node_modules/grunt-ts/tasks/modules/amdLoader.js
npm ERR! M node_modules/grunt-ts/tasks/modules/amdLoader.ts
npm ERR! M node_modules/grunt-ts/tasks/modules/cacheUtils.js
npm ERR! M node_modules/grunt-ts/tasks/modules/cacheUtils.ts
npm ERR! M node_modules/grunt-ts/tasks/modules/compile.js
npm ERR! M node_modules/grunt-ts/tasks/modules/compile.ts
npm ERR! M node_modules/grunt-ts/tasks/modules/html2ts.js
npm ERR! M node_modules/grunt-ts/tasks/modules/html2ts.ts
npm ERR! M node_modules/grunt-ts/tasks/modules/interfaces.d.ts
npm ERR! M node_modules/grunt-ts/tasks/modules/reference.js
npm ERR! M node_modules/grunt-ts/tasks/modules/reference.ts
npm ERR! M node_modules/grunt-ts/tasks/modules/templateCache.js
npm ERR! M node_modules/grunt-ts/tasks/modules/templateCache.ts
npm ERR! M node_modules/grunt-ts/tasks/modules/transformers.js
npm ERR! M node_modules/grunt-ts/tasks/modules/transformers.ts
npm ERR! M node_modules/grunt-ts/tasks/modules/utils.js
npm ERR! M node_modules/grunt-ts/tasks/modules/utils.ts
npm ERR! M node_modules/grunt-ts/tasks/ts.js
npm ERR! M node_modules/grunt-ts/tasks/ts.ts

**Comment by basarat** [comment]
FWIW your code has already been pushed as a part of *other* releases :rose: 

> if I clone the repo, and do a git status... I see that the cloned version has already the not "clean" files..

I am not getting the same behavior : 

image

**Comment by xperiments** [comment]
Ok finally found a way...

The problem seems to be inside the .gitattributes file, if I comment this line:

```
* text=auto
```

And then I do a git status, then the only remaining modified file is the .gitattributes file itself.

So I have modified the .git/info/exclude to exclude the .gitattributes from commit.

Now publishing works.

Cheers!!

**Pull request merged**
