### PR TITLE
Rewrite atom-typescript to use tsserver API

### LINKED ISSUE #1054: [typescript2] - Doesn't recognize types installed by npm i @types/something
First of, amazing job with this package.

So, I have this new project that I'm using `typescript@2` and I decided to give `@types` a shot too.

I have this test file that depends on jasmine, so I installed the types for it by running `npm i --save-dev @types/jasmine`. It has the following content:

``` js
// my_app_test.ts

describe('my-app', () => {
  console.log('yo');
});
```

If I run `tsc`, it compiles just fine, no warnings, no errors - nothing. But, Atom keeps telling me `Cannot find name 'describe'.`. So I figured it should be related to `atom-typescript`.
#### Info
- os: `windows 7, 64bits`
- atom: `1.9.8`
- atom-typescript: `10.1.6`
- tsconfig: 

``` json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "noImplicitAny": true,
        "sourceMap": false
    },
    "exclude": [
        "node_modules"
    ]
}
```

Thanks!

### LINKED ISSUE #1055: [TypeScript 2] Relative paths in typeRoots not resolved (tsconfig.json)
Hi,

I'm having trouble with type definitions being picked up using TypeScript 2/atom-typescript when the `tsconfig.json` is not in the same directory as node_modules. I have a src folder containing `tsconfig.json`, refrencing `../node_modules/@types` in the typeRoots, and a Jasmine test in src/app. atom-typescript does not pick up the Jasmine declarations (e.g. `describe`, `it` etc) and highlights them as errors.

My folder structure is as follows (some folders removed): 

```
- node_modules
-- @types
- src
-- tsconfig.json
-- app
--- app.component.spec.ts
--- app.component.ts
```

My `tsconfig.json` in `src` is as follows:

``` json
{
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es6", "dom"],
    "mapRoot": "./",
    "module": "es6",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ],
    "types": [
      "jasmine"
    ]
  }
}
```

`app.component.spec.ts`:

``` javascript
import { AppComponent } from './app.component';

describe('Example', () => {
  beforeEach(() => {
    // Stuff
  });

  it('should create the app', () => {
    expect(true).toBeTruthy();
  });
});
```

Environment info:

OS: OS X El Capitan 10.11.6
Node.js: 6.3.1
Typescript: 2.0.0
Atom: 1.9.8
atom-typescript: 10.1.6

This configuration works with `tsc` on the command line (either `tsc -p src` in the project root, or `tsc -p .` in `src`). It also works in atom-typescript if I put the entire path in typeRoots - e.g. `/Users/sean/someProject/node_modules/@types` - which makes me think that this is an atom-typescript specific issue in resolving relative paths.

Is this a bug or just something I'm doing wrong with my config?

### LINKED ISSUE #1105: is tsconfig `include` supported?
my project relies on `include` to bring in some typings from a shared folder:

```
"include": [
    "../typings/tsd.d.ts",
    "../../../test/typings/tsd.d.ts",
    "**/*"
],
```

this works just fine in `tsc` or in `webpack` but blows up in Atom, saying that all the typings in both `tsd.d.ts` files cannot be found. **it would seem that atom-typescript is simply ignoring the `include` option so those two extra files are never included in the build.** yet every other typescript environment respects this flag, and it's part of the 2.0 standard.

### LINKED ISSUE #1106: `exclude` spec does not match the official TS 2.0 spec
from https://github.com/TypeStrong/atom-typescript/blob/master/docs/tsconfig.md#options:

> To exclude directories or files from being referenced. This accepts files or folders. **This does not accept glob formatting.**

---

from https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#examples:

**glob support for exclude:**

```
"include": [
    "src/**/*"
],
"exclude": [
    "node_modules",
    "**/*.spec.ts"
]
```

can we please reconcile this? really causing issues with TypeScript 2.0 projects...

### LINKED ISSUE #1134: tsconfig.json parser rejects TypeScript 2.1 and 2.2 options
Example:

```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "es2015",
    "moduleResolution": "node",
    "maxNodeModuleJsDepth": 1
  }
}
```

`"target": "es2016"` and `"target": "es2017"` are also supported options in 2.1 that are rejected by the parser. `"target": "esnext"` is added in 2.2.

### PR DESCRIPTION
**Pull request by guncha**
### What is this? ###

This is a rewrite of the `atom-typescript` package to use a different API when talking to Typescript, but with a lot less features compared to the current implementation.

### Why would you do such a thing? ###

Current implementation relies on Typescript's internals, including undocumented APIs, and does a lot of work to match Typescript's behavior. Unfortunately, Typescript's a moving target and this setup is harder to maintain which no one is doing currently.

For example, if Typescript adds a new `tsconfig.json` option we have to release a new version with updated validation rules. Usually that's trivial, but sometimes it isn't. Supporting something like `extends` would require a non-trivial amount of work.

More importantly, there are a lot of open issues where the behavior of `atom-typescript` doesn't match that of running `tsc` from the command line (closes #1106, closes #1105, closes #1054, closes #1055). There are a few different reasons for those, but they all are caused by `atom-typescript` trying to replicate what the compiler does and the compiler changing what it does over time.

Fortunately, there's a way to let Typescript handle as many details as possible by using their [tsserver API](https://github.com/Microsoft/TypeScript/wiki/Standalone-Server-%28tsserver%29). Unfortunately, this requires rewriting most of the functionality of this plugin.

### Pros for this approach ###

- Let Typescript itself handle most of the details, like tracking files in a project, finding and reading `tsconfig.json` files, etc, which makes the plugin more reliable and eases the maintenance burden.
- Since the tsserver API is mostly backwards compatible and every `typescript` installation comes with a `tsserver` executable, we can use the exact Typescript version from the `node_modules` directory. This remove another cause why `atom-typescript` and running compiler on the command line might disagree about something. This is also more future proof since you don't need to update `atom-typescript` with every new version.

### Cons ###

- Most features need to be re-implemented using this API and some things are not possible altogether since we don't have access to the internals.

Here's a list of things I've implemented so far and others that I haven't:
  - [x] Autocomplete for symbols and types
  - [ ] Autocomplete for modules (the default implementation kind of sort of works for imports)
  - [x] Compile on save (defaults to off unless `tsconfig.json` says otherwise)
  - [x] Error checking (now displayed only with linter)
  - [x] Error checking for tsconfig.json (kind of slow, but works)
  - [x] Build command
  - [ ] Build error view
  - [x] “Check all files in project” command (this is new)
  - [x] Rename refactor
  - [x] Go To Declaration
  - [x] Find references
  - [ ] References view
  - [x] Format command (though not customizable yet)
  - [x] Quick info
  - [x] Highlight the current symbol in the buffer (GIF?)
  - [ ] Symbol view
  - [ ] AST view
  - [ ] Dependency view
  - [ ] “Create tsconfig” command
  - [ ] Quickfixes (!!) (these require manipulating the AST that we don’t have direct access to)
  - [ ] HTML to TSX command
  - [x] The majority of the typings are now from @types
  - [x] strictNullChecks are enabled for all code

### How do I use this? ###

Simply install `atom-typescript-beta` package (https://atom.io/packages/atom-typescript-beta). Make sure `atom-typescript` is disabled as it will not work when both are enabled.

Eventually I'd like to merge this into master, but **only if there's enough support from the community so use your 👍 and 👎 on this issue to let me know what you think**.

### Some GIFs are in order ###

I've basically smushed all the information into the bottom right of the status bar:
image

Build command:
at-build

Symbol highlighting in the same file:
highlight

Closes #1134

### CODE REVIEW

**Comment by merrywhether** [comment]
What are some of the features that will be lost?

**Comment by guncha** [comment]
I'd say most of the things in that list above that are not checked currently. My personal preference would be to have less numerous, but more polished, features instead of porting all of the existing ones over.

**Comment by DanielJoyce** [comment]
Best thing is lack of the double error reports with the old plugin.

**Comment by DanielJoyce** [comment]
Side bonus is since this uses typescript, it appears to work with projects that have multiple TS files in their their heirarchy!

**Comment by basarat** [comment]
Thanks for doing this :rose: Happy to see the excess noisy features go away too :heart: 👍

**Comment by colingreene28** [comment]
Thank you for all your hard work on this. I've installed the beta package and it's working perfectly. I discovered your work through the pain points described in #1054. After installing the beta I was able to pull down types from @types and it just worked :)

Question though. Should issues/PRs come in through here or your new fork?

**Comment by JohnMurga** [comment]
Awesome, thank you 😄 

I am getting an error in :
```
atom-typescript-beta\dist\main\atom\utils\fs.js
```

That I have fixed by adding :

```diff
// Atom uses system dependent path separators while Typescript uses /. Unfortunately, we
// needs this to make sure things like lint errors work.
+ if ( !filePath ) {
+    var filePath = ""
+ }
exports.systemPath = path.sep === "\\" ? filePath => filePath.replace(/\//g, "\\") : filePath => filePath;
```

What would be your preferred way of contributing to your fork ?

**Comment by guncha** [comment]
Thanks @colingreene28 and @JohnMurga. I think it's fine to create issues in the tracker, I'll just tag them as relating to the beta branch. Feel free to open PRs against this branch, too.

**Comment by UnGast** [comment]
Thanks to you I can finally use typescript :)

Would it be possible to set intellisense support for files which contain a <script lang="typescript"> tag on the feature list?

**Comment by ZuBB** [comment]
just got this after installation 

```
/Users/vzuzyak/.atom/packages/atom-typescript-beta/dist/main/atom/components/tsView.js:27
Hide Stack Trace
Error: Failed to execute 'registerElement' on 'Document': Registration failed for type 'ts-view'. A type with that name is already registered.
    at Error (native)
    at Object.<anonymous> (/Users/vzuzyak/.atom/packages/atom-typescript-beta/dist/main/atom/components/tsView.js:27:10)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:109:30)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/vzuzyak/.atom/packages/atom-typescript-beta/dist/main/atom/components/index.js:5:10)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:109:30)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/vzuzyak/.atom/packages/atom-typescript-beta/dist/main/atomts.js:23:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:109:30)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:796:27)
    at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:266:12)
    at PackageManager.module.exports.PackageManager.packageHasSettings (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:51:14)
    at PackageCard.module.exports.PackageCard.hasSettings (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:728:34)
    at PackageCard.module.exports.PackageCard.updateSettingsState (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:402:16)
    at PackageCard.module.exports.PackageCard.updateInterfaceState (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:395:12)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:665:24
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:741:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:607:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:446:26
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:69:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:303:11)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:333:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

is this still relevant?

**Comment by guncha** [comment]
@ZuBB it just means that you have both `atom-typescript` and `atom-typescript-beta` plugins enabled at the same time and they don't play nicely together. Disabling one or the other will take care of that.

**Comment by ZuBB** [comment]
@guncha thanks for your reply.

thats OK. I have disabled original version already.

By the way this beta works really quick and smooth. thanks a lot for you efforts 🙇

**Comment by ZuBB** [comment]
since issues are closed in forked repo ought to do pseudo bug report here
```
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [atom-typescript-beta](https://github.com/guncha/atom-typescript) package 11.0.1


### Stack Trace

Uncaught TypeError: Cannot read property 'executeGetErr' of undefined

```
At /Users/vzuzyak/.atom/packages/atom-typescript-beta/dist/main/atomts.js:79

TypeError: Cannot read property 'executeGetErr' of undefined
    at Object.lodash_1.debounce (/packages/atom-typescript-beta/dist/main/atomts.js:79:24)
    at invokeFunc (/packages/atom-typescript-beta/node_modules/lodash/lodash.js:10350:23)
    at trailingEdge (/packages/atom-typescript-beta/node_modules/lodash/lodash.js:10397:18)
    at timerExpired (/packages/atom-typescript-beta/node_modules/lodash/lodash.js:10385:18)
```

### Commands

```
  6x -0:59.1.0 vim-mode-plus:move-to-next-word (input.hidden-input)
  9x -0:57.1.0 vim-mode-plus:move-down (input.hidden-input)
     -0:54.9.0 vim-mode-plus:move-up (input.hidden-input)
     -0:54.7.0 core:save (input.hidden-input)
  2x -0:54.2.0 tree-view:toggle (input.hidden-input)
     -0:20.2.0 vim-mode-plus:search (input.hidden-input)
     -0:18.5.0 core:confirm (input.hidden-input)
  3x -0:18 vim-mode-plus:repeat-search (input.hidden-input)
     -0:16.1.0 vim-mode-plus:move-to-bottom-of-screen (input.hidden-input)
  9x -0:15.7.0 vim-mode-plus:move-down (input.hidden-input)
  7x -0:14.1.0 vim-mode-plus:move-up (input.hidden-input)
     -0:12.8.0 vim-mode-plus:move-down (input.hidden-input)
     -0:12.5.0 vim-mode-plus:move-up (input.hidden-input)
     -0:12.2.0 vim-mode-plus:move-to-last-character-of-line (input.hidden-input)
     -0:11.5.0 vim-mode-plus:move-left (input.hidden-input)
     -0:06.2.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-shortcuts 0.0.2 
atom-typescript 10.1.14 
atom-typescript-beta 11.0.1 
atom-vim-keymap 1.0.1 
editor-stats 0.17.0 
editorconfig 2.2.2 
ex-mode 0.13.1 
git-control 0.8.2 
git-plus 7.3.3 
goto-definition 1.2.0 
linter 1.11.23 
open-recent 5.0.0 
project-manager 3.3.3 
svg-preview 0.11.0 
sync-settings 0.8.1 
vim-mode-plus 0.82.3 
vim-mode-plus-ex-mode 0.9.0 
webbox-color 0.5.9 
```

I do not have any STR. its just popped out :(

**Comment by jimmytheneutrino** [comment]
>Quickfixes (!!) (these require manipulating the AST that we don’t have direct access to)

Does not tsserver support quickfixes through https://github.com/Microsoft/TypeScript/pull/10185?

**Comment by guncha** [comment]
@jimmytheneutrino no reason it couldn't. The Typescript team has added quite a few quickfixes in the last two Typescript versions so this would be a worthwhile feature.

**Comment by basarat** [comment]
@guncha Just a heads up. You have full executive authority on atom-typescript and are now an owner under TypeStrong. Make `atom-typescript` what ever you want! :rose: :heart:

**Comment by guncha** [comment]
Thanks @basarat! Any ideas how to smoothly transition to the version in this branch?

**Comment by basarat** [comment]
> Thanks @basarat! Any ideas how to smoothly transition to the version in this branch?

Rename `master` to `legacy` and rename this branch to `master` :rose: 👍

**Comment by ZuBB** [comment]
I got new error with beta version https://gist.github.com/ZuBB/d35eb7530a142ce3aaf3fc62abc8268e

**Comment by guncha** [comment]
Thanks @ZuBB, it'd be great if you could open an issue in this repo and I'll tag it with `beta`. It's probably my lazy implementation of the `tsserver` protocol 😄

**Comment by basarat** [comment]
Wohooo 🌹 Looking forward to installing it ❤🤗

**Comment by guncha** [comment]
Awesome 😊 I expect to wake up to a million complaints, but we'll get through it..

**Comment by aseemk** [comment]
Wow! Amazing work. =)

**Pull request merged**
