### PR TITLE
Support tsconfig "typeRoots" compiler option

### PR DESCRIPTION
**Pull request by seanchas116**
[x] All compiled assets are included (atom packages are git tags and hence the built files need to be a part of the source control)

This pull request adds `typeRoots` compiler option in tsconfig. http://json.schemastore.org/tsconfig

### CODE REVIEW

**Comment by adamduren** [comment]
@basarat @seanchas116 Any update on this? This along with other flags such as `lib` included in `angular-cli` are causing Atom to not be able to load the project.

**Comment by basarat** [comment]
Released this with `10.1.6` :rose:

**Comment by adamduren** [comment]
Thanks!

**Comment by einfallstoll** [comment]
Does this really work? I've defined `typeRoots` as `["./node_modules/@types/"]` and installed `@types/node` but I get an error when using `module.id`. If it's a bug, I'll open an issue.

**Pull request merged**
