### PR TITLE
Clean up build process to separate compiled content from raw content

### PR DESCRIPTION
**Pull request by park9140**
Removing node modules as it is bad practice to include this in a repository.  

Moving compiled content to 'dist' directory for better separation while developing. 

Including map files to make debugging simpler.

Update out of date libraries.

### CODE REVIEW

**Comment by park9140** [comment]
@basarat, I think this makes it much easier to work on the code.  I have a few things I need to add before I can use this in the office.  After this I intend to attempt to rectify the 600+ ms startup time, and depricated api usage.

**Comment by basarat** [comment]
Glad I didn't do a push. I'll merge and then commit my stuff :heart:

**Comment by basarat** [comment]
> Including map files to make debugging simpler.

did it really help? I didn't see atom picking it up when I tried : https://github.com/TypeStrong/atom-typescript/issues/123

**Comment by basarat** [comment]
Nope. Sourcemaps don't work : 
image

It's because our JS gets wrapped by atom in `(function (exports, require, module, __filename, __dirname) {` and `});`

So sourcemaps are no longer valid : 
image

I'd be more interested in adding TypeScript support directly into atom once I get a chance. Looking at the recent `6to5` support its not that hard to do.

**Comment by basarat** [comment]
@park9140 also, we are building with atomts instead of `grunt` : https://github.com/TypeStrong/atom-typescript/commit/613435082239e8032acedcff964584527fb23ede 

`grunt` is now there just for backup (when things go bang during development).  Also note `const enum` handling is broken in the `1.4` language service : https://github.com/TypeStrong/atom-typescript/commit/613435082239e8032acedcff964584527fb23ede#diff-4e626b81616e50c89d68cba32c8d4c51L34 so if the last build isn't from `atomts` then the output would mismatch and there will be conflicts :+1:

**Comment by csnover** [comment]
> @park9140 also, we are building with atomts instead of grunt : 6134350 

Nobody will know if the documentation is not kept up to date :) https://github.com/TypeStrong/atom-typescript/blob/master/CONTRIBUTING.md#building

**Comment by basarat** [comment]
@csnover on it

**Comment by basarat** [comment]
@park9140 if sourcemaps indeed don't work for you as well delete them from the repo, grunt file,tsconfig. Or give me the go ahead ❤️

**Comment by park9140** [comment]
@basarat, will do,  I popped my debugger up and thought I was seeing them, but I'll take another look, maybe I had some weird setting, I played with adding direct typescript support before and may have enabled something that made them work.

**Pull request merged**
