### PR TITLE
Modify the README about how to disable CompileOnSave

### PR DESCRIPTION
**Pull request by remaerd**
Hi,

I'm creating this pull request to modify the README.md about how to disable CompileOnSave. So you don't need to be asked by different people with a same question like me.

Cheers.

### CODE REVIEW

**Comment by nycdotnet** [comment]
Hi @remaerd. Thank you so much!

Two minor fixes and I'll merge this.  Can you fix the spelling of automatically, and also "this feature. add" should be a comma not a period.

Thanks for the follow-up.  We're glad you find atom-typescript useful.

**Comment by basarat** [comment]
Thanks @nycdotnet  :rose: :rose: 

@remaerd its there in the FAQ : https://github.com/TypeStrong/atom-typescript/blob/master/docs/faq.md But what you have is fine too :rose:

**Comment by basarat** [comment]
those two roses were intentional :)

**Comment by nycdotnet** [comment]
I'm feeling the love.

**Comment by nycdotnet** [comment]
Thanks @remaerd !

**Pull request merged**
