### PR TITLE
changing out parameter to outFile

### LINKED ISSUE #883: outFile option prevents output
When adding the `outFile `option in _tsconfig.json_, the **output is not generated**.

See the minimalist attached example:
When the `outFile` option is removed, the output files are generated (but in several files).
When using tsc in the command line, the output is generated.

**Config:**
atom 1.5.4
atom-typescript 8.3.0
typescript 1.8.7
Windows 10

[test.zip](https://github.com/TypeStrong/atom-typescript/files/172188/test.zip)

### PR DESCRIPTION
**Pull request by iTouchTheSky**
resolves #883

### CODE REVIEW

**Comment by iTouchTheSky** [comment]
I think I messed up with the version I though I had to do `apm publish patch`, could you please check that out @basarat or is it ok like this ?

**Comment by basarat** [comment]
Looks great :rose: You should need to update `package.json` as that is something that happens during deployment (when project owners like myself run `apm publish patch` *to deploy*) aka ... PRs don't need to run this :)

**Comment by basarat** [comment]
Don't worry ... I got this :rose: Just lay back and relax :+1:

**Comment by iTouchTheSky** [comment]
Alright, thanks ! :smile:

**Comment by basarat** [comment]
https://github.com/TypeStrong/atom-typescript/releases/tag/v8.3.1 :rose: Hopefully this doesn't break `out`

**Comment by iTouchTheSky** [comment]
Badum Tsssss !

**Pull request closed without merging**
