### PR TITLE
Re-Adding Symbols View (#1219)

### PR DESCRIPTION
**Pull request by russaa**
- [x] All compiled assets are included (atom packages are git tags and hence the built files need to be a part of the source control)

Re-adding `symbols-view` for project- and file-symbols  
-> see discussion in #1219

This PR is based on the `symbols-view` system package with some small modifications:
 * code integration/modifications for including it here as TS resources
 * replaced `ctag` parser with `tsserver` commands `navTree` (for file symbols) and `navto` (for project sybmols)

It also includes keyboard shortcuts for overriding the `symbols-view` shortcuts if a TS file editor window is focused (i.e. `ctrl-/cmd-r` and `ctrl-/cmd-shift-r`).

### CODE REVIEW

**Comment by lierdakil** [comment]
Sorry, I changed a bunch of architecture-related stuff on `master, could you rebase?

Most notably, feature registration moved from `atomts.ts` to `lib/main/plugin-manager.ts` (since it's easier to manage lifetimes that way), and command registration changed up a bit in `lib/main/atom/commands`.

Overall, this feels like *way* too much code for something as simple as "show symbols for file/project". At least views seem to be crazily overengineered. It would seem to me, in most cases, a simple call to `selectListView` from `lib/main/atom/views/simpleSelectionView.tsx` would suffice. Maybe let's try to simplify because I *really* don't want to end up maintaining this mess.

**Comment by russaa** [comment]
As I mentioned:  
this is basically a copy of the files from `symbols-view`.

So, in my understanding, maintaining would mean:
 * diff with `symbols-view` and transfer changes
 * maintain additional/custom code (mainly with regard to using `tsserver` and converting the results to a format that `symbols-view` "understands)

So rather than re-implementing this, I would prefer to make the changes more explicit (where that is not already done), so that the "diff & transfer from `symbols-view`" portion of maintenance is painless

Of course the require re-formatting in `atom-typescript` makes this a bit more difficult, but it's still pretty straight forward.  
Also: `symbols-view` seems to be pretty stable, i.e. is not updated too often.

Ideally at some point, the `symbols-view` package may be opened up to allow different providers (other than ctag-parsing), at which point these views could be removed again.

**Comment by russaa** [comment]
... still I think, it would be better to keep the _copy_ as is:  
 * regardless what reason, updates from `symbols-view` should be required very rarely
 * and you'd only really need to update/transfer changes, if something breaks or the UI significantly changes in `symbols-view`

-> so I would maybe extract all changes from the current files (i.e. keep the copies as close to the original as possible, except for the necessary changes due to conversion to Typescript) 
-> include the changes by extending the original/base classes

and make formatting exceptions for the original/base class files

Then in almost all instances, you'd only look at the modification/extending files, and leave the original/base class files as is.

I had a quick look at what could be removed: it would be mostly stuff to watch for file-changes (which would trigger ctag-parsing/updates) and loading the ctag-caching files ... I did not find too many places with code for this, so I think, that --if you want to keep the `symbols-view` behavior-- you need to keep most of the code.

Let me know what you want to do:  
if you decide to pursue the option of "keeping the copies", I could make the changes that I suggested above (extract the modifications to extra files, and keeping the original/copied files as close to the `symbols-view` implementation files as possible).

**Comment by lierdakil** [comment]
I might have gotten a little carried away with this... Anyway, it seems most of what could be done has been done here. So I'll merge this if that's okay with you.

**Comment by russaa** [comment]
looks all good to me 👍 

_I mean to symbols-view part -- to be honest, I did not look too much into the other stuff regarding position history etc_

**Pull request merged**
