### PR TITLE
fix for highlighting

### PR DESCRIPTION
**Pull request by stepancar**
fix for https://github.com/TypeStrong/atom-typescript/issues/666

### CODE REVIEW

**Comment by stepancar** [comment]
@basarat , i just go[ to babel]( https://github.com/babel/babel-sublime/blob/master/JavaScript%20(Babel).YAML-tmLanguage) then to json, then to cson. 
As i see issue fixed

**Comment by basarat** [comment]
Sure ... why not :rose: 

Note : if something breaks in the next few days I will undo this and tag you in :)

**Comment by basarat** [comment]
closes #666

**Comment by basarat** [comment]
Released https://github.com/TypeStrong/atom-typescript/releases/tag/v7.4.3 :rose:

**Comment by basarat** [comment]
Note to myself : similar PR in atom-react : https://github.com/orktes/atom-react/pull/105

**Pull request merged**
