### PR TITLE
Adds "AddClassMethod" quick fix

### PR DESCRIPTION
**Pull request by xperiments**
Based on the addClassMember.ts, adapted to my needs.

### CODE REVIEW

**Comment by basarat** [comment]
Would love a screen2gif to see expected behavior 🌹

**Comment by xperiments** [comment]
Some gifs here... Also updated code to support normal scenarios, yesterday code was not really this:


complextypes
methodreferences
simpletypes

**Comment by basarat** [comment]
Sweeeeet

**Comment by xperiments** [comment]
Thanks!! preparing a new PR to better support strange scenarios...

**Pull request merged**
