### PR TITLE
[RDY] Improve grammar.

### PR DESCRIPTION
**Pull request by Cu3PO42**
Originally coming from TypeStrong/atom-typescript#410 I started improving the grammar. I stumbled upon more things than originally noted there, though and am trying to get as much fixed as possible.

I added TODOs for everything I noticed so far and that isn't handled completely. Unfortunately that's still quite a bit, but I thought I'd share my progress so far.

**EDIT**: All TODOs handled.

### CODE REVIEW

**Comment by basarat** [comment]
That's a lot of work and code quality is :100:

There is also this : https://github.com/Microsoft/TypeScript-Sublime-Plugin/blob/master/TypeScript.YAML-tmLanguage and (I believe generated https://github.com/Microsoft/TypeScript-Sublime-Plugin/blob/master/TypeScript.tmLanguage) If you are curious more about these. 

Thanks a lot for this. I'd be happy to press the `merge` button whenever you want :rose:

**Comment by Cu3PO42** [comment]
Thanks for the feedback @basarat! I'm happy to help. When I'm done here, I'll post some screenshots, squash the commits and mark this [RDY].

**Comment by Cu3PO42** [comment]
@basarat Looks like I'm pretty done here. That was more work than I anticipated.

I'll also create a branch for the One Dark color scheme and add the few TS specific things here, reference that here and send a PR to them when this one is merged :)

**Comment by nycdotnet** [comment]
Wow!

**Comment by Cu3PO42** [comment]
Had a quick idea there... Guess I wasn't quite as done as I thought.

**Comment by Cu3PO42** [comment]
And of course, I did forget a final thing...

**Comment by basarat** [comment]
Let us know when it's good to merge and no more pushes are coming ;)

**Comment by Cu3PO42** [comment]
@basarat I thought it was when I tagged it RDY, however after doing some development in TS, well, I found some cases I missed.

At this point it is most certainly bug free and can be merged. If I happen to find more things I missed, well, I'll open a new PR.

**Comment by basarat** [comment]
:rose: Let me use it for one day :+1: before pushing

**Comment by basarat** [comment]
function parameter (although correct), is a bit too aggressive : 

image

Perhaps its needs a nested recursion?

**Comment by basarat** [comment]
Commented out offending rule for now so that it doesn't block remaining good stuff :rose: from release ;)

**Comment by Cu3PO42** [comment]
The theme I used did actually not highlight function parameters, so I didn't see that. What would you consider to be the "correct" behavior? Match the braces, but not what's in between, match everything that doesn't recurse? And just for my own reference, that theme is Monokai, right?

**Comment by basarat** [comment]
> And just for my own reference, that theme is Monokai, right?

yes

> . What would you consider to be the "correct" behavior? Match the braces, but not what's in between, match everything that doesn't recurse?

Actually `parameter` is different from `arguments`. Perhaps we can leave `arguments` unhighlighted (and let their natural tokenization take over) , which is what the js grammar does:

image


Note: The typescript ast also `arguments` vs. `parameters` which you can check using the ast visualizer on the following:

```
function foo(a){
}
foo('asdf');
```

Also note: I know less about how `cson` grammars work than you do at this point :)

**Comment by Cu3PO42** [comment]
The distinction between arguments vs parameters in JS and other C like grammars was actually the first thing I was going to check when I got to my PC (early morning here). Seeing as it appears to be the way I expected, I'm all in favor of just deleting that specific rule.

Actually I only added it in the first place because the original TS grammar I started from would have "tried" to match that. But, yeah, just delete it :)

I would hope I know some things about TextMate grammars now! Though I had never seen one in my life before I started this.

**Comment by basarat** [comment]
> just delete it

Done! Been using it all day and it looks much prettier. Published with a major version : `5.0.0` (the actual breaking change is that we don't create a tsconfig.json for you ... the user needs to trigger a command and we inform the user to do so).

Thanks for you hard work :rose: :100: :star:

**Comment by Cu3PO42** [comment]
You're quite welcome! Glad it looks good and that my work can get out to everyone. I'm honestly not all that familiar with tsconfig files, but I don't quite get why this needs a special case... Why would you create a tsconfig file for CSON?

Not that it matters, I'm just curious.

**Comment by basarat** [comment]
> Why would you create a tsconfig file for CSON

Sorry for the confusion, `tsconfig.json` has got nothing to do with cson.

I meant that, I didn't do a version major (from `v4` to `v5`) upgrade because of *this* PR. I did that because of some other breaking change : https://github.com/TypeStrong/atom-typescript/blob/master/docs/CHANGELOG.md#v500

**Comment by Cu3PO42** [comment]
I see, I actually had that thought after looking at Changelog.md. Just a misunderstanding there, thanks for clearing it up!

**Comment by basarat** [comment]
Have a minor request notice `public` on member property vs. function :

image

No hurry and feel free to say *no* :)

**Pull request merged**
