### PR TITLE
Updated typescript version, to pickup additions

### PR DESCRIPTION
**Pull request by david-driscoll**
@blakeembrey @nycdotnet @Cu3PO42 (and anyone else)

Think we can push a release through at all with the updated services, running into a few bugs that have been fixed by the latest TS releases.

### CODE REVIEW

**Comment by blakeembrey** [comment]
I think we want to stick to pinning releases. Things could break randomly in the future otherwise.

**Comment by david-driscoll** [comment]
whoops, good 'ol tool that updates the values, updated the PR.

**Comment by blakeembrey** [comment]
I'll look at doing a release soon :+1:

**Comment by david-driscoll** [comment]
rock on... I'll try and make some time to work on the plugin a little bit more, help solve some of the issues I run into, that I imagine others do too. :smile:

**Pull request merged**
