### PR TITLE
explicitly add compile on save and build on save on generated tsconfig

### LINKED ISSUE #758: initial generated tsconfig - add buildOnSave and compileOnSave with their defaults
Usually I build typescript using a custom build. Each time I generate a tsconfig.json file on a new project, I forget to add the build options, and also forget the [exact syntax](https://github.com/TypeStrong/atom-typescript/blob/master/docs/faq.md#i-dont-want-atom-typescript-compiling-my-js) :)
I'd like to add the defaults to tsconfig so me including others can clearly see it and switch to false without too much thinking.
```
"compileOnSave": true,
"buildOnSave": true,
```
For better usability. I'll send a PR soon if this sounds right.

Thanks, the plugin is amazing!

### PR DESCRIPTION
**Pull request by GabiGrin**
explicitly add 2 options that come as "silent" defaults
fixes #758

### CODE REVIEW

**Comment by basarat** [comment]
Thanks! however `buildOnSave` is not true by default (as build is a slow process). Leave a comment once updated :rose:

**Comment by GabiGrin** [comment]
Oops :blush: 
Fixed

**Comment by basarat** [comment]
Will be the part of the next release :rose:

**Comment by GabiGrin** [comment]
Awesome! thanks :smile:

**Comment by basarat** [comment]
released : https://github.com/TypeStrong/atom-typescript/releases/tag/v7.13.0 :rose:

**Pull request merged**
