### PR TITLE
Update grammar files

### PR DESCRIPTION
**Pull request by admosity**
Generated new grammar files to fix/alleviate numerous highlighting issues.

Examples with new grammar from multiple issues:

#1080
image

#1061
image

#1004
image

Upstream changes for decorator highlighting:
Microsoft/TypeScript-TmLanguage#329
image

### CODE REVIEW

**Comment by guncha** [comment]
This is great and long overdue! The problem I had last time when trying to do this was that:

1. My Atom theme aggressively colored every identifier red
2. The `.tsx` grammar was broken

Can you please make sure it still works with `.tsx` files?

**Comment by admosity** [comment]
1. It looks great right now with the monokai theme. I think there might need to be some tweaks with some selectors.
2. It doesn't parse at all 😭

**Comment by admosity** [comment]
Looks like the big issue is that the file generated for `.tsx` is truncated. I'll take a look at the script and see what's going on there.

**Comment by admosity** [comment]
image

I loaded the last fuller grammar file defined. This seems to play nicer. I'm not that familiar with `.tsx` syntax, but it seems to be able to parse html tags wherever you place them with this grammar. Looks generally okay.

**Comment by admosity** [comment]
Looking into why that file is so short. Maybe they're combining the two to make the other files so we would have to do the same.

**Comment by guncha** [comment]
It looks like to me that the truncated grammar file only contains JSX related bits and not the whole Typescript grammar, so I think we're expected to reference or include it in the main Typescript grammar to generate a `.tsx` grammar. Perhaps creating a copy of the Typescript grammar, appending all of the grammar expressions from the JSX one and then adding `{ include: "#jsx" }` to the `expression` patterns would do the trick.

**Comment by admosity** [comment]
Yep figured it would be that. I'll look into implementing that later today when I'm not swamped with work.

**Comment by guncha** [comment]
I just had some limited success with it, but it will definitely need some tweaking and automation:

image

Btw, I had to remove the `cast` pattern as it's not valid in a `.tsx` file.

**Comment by admosity** [comment]
Yep I'll load in those xml files and swap out the yaml parser for an xml parser. I'll give that a go later tonight and see the results.

**Comment by guncha** [comment]
@admosity I had some time to do it today and it seems to work ok. I'll open a PR in a sec.

**Comment by admosity** [comment]
Shucks, I'll have to look elsewhere for my hacktoberfest submission. 😆

**Comment by guncha** [comment]
Haha, sorry, this has been on my mind for a while now 😄
Feel free to pick anything from the issue tracker here 😉

**Pull request closed without merging**
