### PR TITLE
feat(console.log):  snippet

### PR DESCRIPTION
**Pull request by andreasonny83**
Add support for `console.log` snippet

### CODE REVIEW

**Comment by guncha** [comment]
I simplified it to avoid using quotes and a semicolon to make it a more agreeable default. Most people will have their own snippet for this anyway, but it's good to have in the package. Thanks!

**Comment by andreasonny83** [comment]
looks good. thank you!

**Comment by andreasonny83** [comment]
@guncha, is it possible to trigger a new release containing this new feature?

**Comment by guncha** [comment]
Yeah, doing that right now.

**Pull request merged**
