### PR TITLE
Issue 818/angular component html highlighing

### PR DESCRIPTION
**Pull request by GregOnNet**
**EDIT** Please refer to #949 first because it will fix the build-error occurring here.

Hi,

I added a custom grammar to `scripts/grammar.js` enabling html syntax highlighting inside Angular's `@Component` decorator.

The result looks like this.

book-details_component_ts_ __users_gregor_development_projects_angular_book_book-monkey2

Please let me know if this is valuable for you or if I you need further information.

Kind Regards
Greg

### CODE REVIEW

**Comment by fmalcher** [comment]
:+1:

**Comment by ralfe-software** [comment]
good work and very useful :+1:

**Comment by JohannesHoppe** [comment]
i definitely would like use this feature :+1:

**Comment by MarkPieszak** [comment]
Huge win for Atom & Typescript here 👍

**Comment by blakeembrey** [comment]
LGTM 👍 How does this work with an escaped back tick? Is it handling it?

**Comment by GregOnNet** [comment]
Do you mean something like \``<span>`\``content</span>`\`? 

I will test it when I am back at home today.

**Comment by blakeembrey** [comment]
Yeah, just one in the middle.

~~~html
`<span>\`content</span>`
~~~

**Comment by GregOnNet** [comment]
@blakeembrey Good point. It was not managing escaped back ticks.
I updated the regex by adding a negative look behind to the RegEx: https://regex101.com/r/hV8rS2/1

I have to thank the whole `atom-typescript`-Team for the great work you have done! 👍 

Now it shall work.

book-details_component_ts_ __users_gregor_development_projects_angular_book-monkey2

//cc @basarat

**Comment by blakeembrey** [comment]
Seems good to me, I'd like to leave @basarat to handle now 😄

**Comment by basarat** [comment]
Thanks everyone :rose: https://github.com/TypeStrong/atom-typescript/releases/tag/v8.10.0

**Comment by albtdd** [comment]
Great, It works for me!
Thank you!

**Comment by GregOnNet** [comment]
You are welcome, sir. 😃

**Pull request merged**
