### PR TITLE
Allow using baseUrl, paths and rootDirs options in tsconfig,json

### PR DESCRIPTION
**Pull request by guncha**
This is largely based on the work @laurelnaiad did in #849. I mainly just upgraded ntypescript and fixed a few things that broke along the way as well ensured that the baseUrl and rootDirs get converted to absolute paths.

### CODE REVIEW

**Comment by zaaack** [comment]
+1

**Comment by guncha** [comment]
@basarat, this is the last missing piece to let my team migrate over to using reasonable import paths and I'm wondering if you have any concerns about the PR. If so, please let me know and I can address them.

**Comment by basarat** [comment]
> I'm wondering if you have any concerns about the PR

None. I trust you :rose:

**Comment by basarat** [comment]
Released with `10.1.0` as a minor version upgrade :rose:

**Comment by guncha** [comment]
Thank you, I appreciate it.

**Comment by tomitrescak** [comment]
You are stars! Thanks! 👏

**Pull request merged**
