### PR TITLE
Auto format on save

### PR DESCRIPTION
**Pull request by lordmat0**
#810 

I wasn't sure if this should be a default on, so I decided to have it defaulted to off.

### CODE REVIEW

**Comment by basarat** [comment]
> so I decided to have it defaulted to off.

Definitely. Don't want user to open someone else's project's typescript file for quick editing just to have it change on them :rose:

**Comment by basarat** [comment]
Please answer: Can you try on a project that doesn't have the `atom` key already. Does it work (the tsconfig.json shouldn't be modifed and format on save shouldn't happen and there should be no errors in the atom debug console)? :rose:

**Comment by lordmat0** [comment]
I tried it already, it works correctly :)

We create the key here:
https://github.com/lordmat0/atom-typescript/blob/auto_format_on_save/lib/main/tsconfig/tsconfig.ts#L402-L406

Before I use it here:
https://github.com/lordmat0/atom-typescript/blob/auto_format_on_save/lib/main/tsconfig/tsconfig.ts#L445



Would it also not be worth adding it as a menu item?

**Comment by basarat** [comment]
> Would it also not be worth adding it as a menu item? so others using atom on the same project don't have to share the same setting.

You mean *atom config* item? No. Its good to have this shared as a requirement on using the project :rose:

**Comment by basarat** [comment]
Released : https://github.com/TypeStrong/atom-typescript/releases/tag/v8.1.0 :rose:

**Comment by s00500** [comment]
Has this feature been removed again? Why?

**Pull request merged**
