### PR TITLE
Fixing Travis CI Build

### PR DESCRIPTION
**Pull request by GregOnNet**
I experienced an error building my pull-request: https://github.com/TypeStrong/atom-typescript/pull/948

First I that the error my relates to my changes but this is not the case.

The problem is located in `quickfixes/stringConcatToTemplate.ts`.
There was a function declaration within a while-loop causing `$ npm test` to throw an error.

I moved the concerned method (appendToFinal) into a private method.

Please have a look to my changes.

Kinds
Greg

### CODE REVIEW

**Comment by basarat** [comment]
A thousand :hearts:

**Comment by basarat** [comment]
I'd like to fast track your stuff. If you have any PRs please @ mention me :rose:

**Comment by basarat** [comment]
https://github.com/TypeStrong/atom-typescript/releases/tag/v8.9.2 :rose:

**Comment by GregOnNet** [comment]
Thank you very much for the kind words. 😃 
For future PRs I will mention you, thanks.

**Pull request merged**
