### PR TITLE
add systemjs import syntax support to quick fix

### PR DESCRIPTION
**Pull request by jschwarty**
Couple of thoughts on possible changes to this PR:

- I used the project file compiler options to identify if that is set to use "system" in order to make the decision on the syntax for the import statement. Not sure if this is ideal or not...
- I hard coded double quotes similar to the current statement, but could this be changed so the single/double quote setting from atom would be used here?

### CODE REVIEW

**Comment by jschwarty** [comment]
I am thinking that the `tsconfig.json` compiler module setting should not be the deciding factor because in Angular2 the compiler options need to be module "commonJs", so maybe a package setting that allows a user to configure the import syntax?

**Comment by basarat** [comment]
@jschwarty thanks Justin! :rose: 

> I used the project file compiler options to identify if that is set to use "system" in order to make the decision on the syntax for the import statement. Not sure if this is ideal or not.

Not. Please create a *new* quickfix entry instead of replacing the current one. Let the user decide. Copy paste into a new file is fine :rose:

> but could this be changed so the single/double quote setting from atom would be used here

Not easily as the code is running in the *backend* worker that has limited `atom` API access so might not work or break in the future. I wouldn't do it :rose:

**Comment by jschwarty** [comment]
Ok, I will be afk for the weekend so I will make these changes at the start of next week and update the PR. Thanks!

**Comment by nycdotnet** [comment]
Thanks Schwarty!

**Comment by jschwarty** [comment]
Created a new PR (https://github.com/TypeStrong/atom-typescript/pull/791) with the suggested approach...

**Comment by amb-it-ion** [comment]
I got a missing dependency "Cannot find name <xyz>", but get no quick fix suggestion. I am on version 7.16.1. Any advice?

Thanks for your work - this feature is much needed.

**Pull request closed without merging**
