### PR TITLE
Optional transpilation with Babel

### PR DESCRIPTION
**Pull request by nycdotnet**
I became despondent the other day when I saw that the `let` keyword's special scoping rules in `for`-loop iterators wouldn't be transpiled properly by TypeScript 1.5 to ES5.  https://github.com/Microsoft/TypeScript/issues/3915

While I am pleased that @danquirk seems amenable to implementing this in TypeScript, and I agree with @basarat that doing so [is the best long-term solution](https://github.com/TypeStrong/atom-typescript/issues/469#issuecomment-122177243), it could take some time.

Since this feature of `let` is transpiled properly by Babel today, I wondered if I could put together an enhancement for atom-typescript to optionally run the JS emitted by the TypeScript language service through Babel during the compile-on-save process.  As Bas predicted, it was actually fairly straight-forward, and this pull request is the result.

This PR utilizes a new optional key in tsconfig.json:
```json
{
    "externalTranspiler": "babel"
}
```

If key exists exactly as above, the emitted JS from the TS language service will be run through Babel; if not, it's not.

I would love your feedback on this.  Bas - would you consider merging?  I am open to any and all suggestions with regards to the config file, key names, etc.

**ToDo:**

- [x] Transpilation with Babel works based on the presence of a key in tsconfig.json.
- [x] Confirm source maps and other options are passed appropriately
- [x] Document
- [x] Test install/uninstall atom-typescript works as expected.  (Everything worked when I deleted the contents of my `%userprofile%\.atom\packages\atom-typescript\node_modules` folder and then ran `apm install`, so I am hopeful this is fine.

### CODE REVIEW

**Comment by basarat** [comment]
@nycdotnet I'd be happy to merge and support this till typescript has emits for "let with closure" as well as "async await"

Till then typescript currently supports both these things with target es6. I think it provides great value to allow people to chain the typescript type checker and babel transpiler ie others have asked for it as well. So merge at will and thanks! 🌹

**Comment by basarat** [comment]
And the name you have chosen seems to be worth supporting till infinity!

**Comment by johnnyreilly** [comment]
+1 for this!

**Comment by nycdotnet** [comment]
@basarat I believe that this is ready.  It actually seems to work shockingly smoothly for something I coded, especially with the fixes you made yesterday.  Would you please eyeball this and merge/release if you feel happy?

Note: I'm not quite sure of the best way to test uninstall/reinstall of atom-typescript without actually releasing it.  Are all the modules referenced in `package.json` always automatically downloaded by a package?

**Comment by basarat** [comment]
> Are all the modules referenced in package.json always automatically downloaded by a package

node_modules? Yes. As a part of `apm update` which is what the users use (either manually or through the settings view). For us (`git clone` users), we need to run `npm install` as mentioned : https://github.com/TypeStrong/atom-typescript/blob/master/CONTRIBUTING.md#pull (could be improved on second look)

**Comment by basarat** [comment]
:FANCY:

**Comment by basarat** [comment]
Pushed with `5.2.0`. Lets see how it goes in userland :+1:

**Pull request merged**
