### PR TITLE
Replace resolve logic with `tsconfig`

### LINKED ISSUE #651: filesGlob excludes no longer work in 7.3.0
My use case:
~~~
    "filesGlob": [
        "./cdn_source/**/*.ts",
        "./cdn_source/typings/**/*.ts",
        "./scripts/typings/**/*.d.ts",
        "./cdn/aurelia/**/*.d.ts",
        "!./node_modules/**/*.ts",
        "!./cdn/aurelia/node_modules/**/*.ts",
        "!./cdn/aurelia/jspm_packages/npm/rx@*/ts/**/*.ts",
        "./cdn/aurelia/jspm_packages/npm/rx@*/ts/rx.all.es6.d.ts"
    ],
~~~

but all rx@ ts files are included in files section now.
I've tried different orders but doesnt seem to help.

### PR DESCRIPTION
**Pull request by blakeembrey**
Closes #651. References #646.

Turns out it wasn't difficult to replace the parts you were using, and all the validation stays the same :smile:

### CODE REVIEW

**Comment by blakeembrey** [comment]
Actually, there's one thing missing - let me add that. It's not updating `files`.

**Comment by blakeembrey** [comment]
@basarat Done. Made a new release with `glob` for `tsconfig` and only needed to change the `prettyJSON` output to go back to relative paths (making them "consistent" now too). I also added a  feature to make sure indentation is persisted for `tsconfig.json`.

**Comment by nycdotnet** [comment]
Can you publish?  If not would you like me to?  Bas won't be on for several hours.

**Comment by blakeembrey** [comment]
Sure, I can do it :+1:

**Comment by blakeembrey** [comment]
Done. `v7.4.0`.

**Comment by basarat** [comment]
Awesome. Thanks a ton for this .... I would have never managed to put in so much effort :rose:

**Pull request merged**
