### PR TITLE
[RDY] Further improve grammar.

### PR DESCRIPTION
**Pull request by Cu3PO42**
It was brought to my attention that a few things were added to TypeScript since I last used it on a larger scale and not all of these work properly right now. Specifically these are tuple types, indexable types and deconstructing in assignments. I'll try and get the things out there ASAP.

### CODE REVIEW

**Comment by basarat** [comment]
> I'll try and get the things out there ASAP.

No hurry. Do them at your *pleasure* :rose:

**Comment by Cu3PO42** [comment]
@basarat I think we're good here, but you probably want to double check :)

**Comment by basarat** [comment]
Merge at will and then `apm publish patch`

Also you might want to do `git config --global credential.helper wincred` if on windows to make workflow easier

**Comment by Cu3PO42** [comment]
I'm pretty sure there are no bugs here, but I'll test for a bit longer and then merge!

And I'm on OS X, but thanks for the hint :)

**Pull request merged**
