### PR TITLE
Make panel body padding consistent with header

### PR DESCRIPTION
**Pull request by blakeembrey**
Follow up on #607 to fix a minor padding visual issue (forgot to check with the panel open).

image

Edit: There's definitely some work to do on smaller screen widths.

### CODE REVIEW

**Comment by blakeembrey** [comment]
Make some fixes for the smaller screen layout:

image

**Comment by blakeembrey** [comment]
However, once the summary is populated it forces it to overflow - I'll try to look into it.

**Comment by blakeembrey** [comment]
Depends whether this is an issue, but overall it lays out a bit better:

image

**Comment by blakeembrey** [comment]
@basarat I definitely recommend you review this a little before merging, I've been using it today and have found a few different states I didn't initially see - overall it's much cleaner and a little tighter now (using smaller margins) in some places).

**Comment by basarat** [comment]
Good call with the wrap. Looks great :rose:

**Comment by basarat** [comment]
`6.0.18`

**Pull request merged**
